
// This file was auto-generated by ML.NET Model Builder. 

using AnimalClassifier_ConsoleApp;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\user\Desktop\AnimalClassifier\AnimalClassifier\images\cat\125774-morda-dikaya_koshka-bakenbardy-polosatyj_kot-norvezhskij_lesnoj_kot-3840x2160.jpg");
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
